site_name: FPCMCI
site_author: 'Luca Castri'

theme:
  # name: 'mkdocs'
  name: 'material'
  palette:
    
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/logo.png
  favicon: assets/icon.png


plugins:
  - search
  - mkdocstrings
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math


nav:
  - Overview: index.md
  - Preprocessing: preprocessing.md
  - Subsampling: subsampling_method.md
  - Feature Selection Methods: feature_selection_method.md
  - FPCMCI: fpcmci.md
  - DAG: DAG.md